### ISSUE TITLE
feature: svg export

### ISSUE THREAD

**Issue by derStephan** [dataweb-GmbH/NShape#1]
Hi,

thanks for NShape. Using it a lot to draw flow charts. 

In my opinion, a export to svg would be a perfect addition. Any chance of implementing it?

**Comment by kholzinger** [comment]
Not in the near future, sorry.

**Comment by derStephan** [comment]
Will there be any development in the near future?

**Comment by kholzinger** [comment]
Currently, we are working on a new release but there is no release date yet.

**Comment by derStephan** [comment]
I see. I thought, Nshape was abandoned. There was no commit for 2 years. Anyway, Nshape is working fine so maybe there is nothing to do.
