### ISSUE TITLE
Dependencies of Nuget Packages declared wrong

### ISSUE THREAD

**Issue by mkaring** [dataweb-GmbH/NShape#6]
[`NShape.Shapes.General`](https://www.nuget.org/packages/NShape.Shapes.General/) and [`NShape.WinFormsUI`](https://www.nuget.org/packages/NShape.WinFormsUI/) 2.4.0 declare  the dependency to `NShape.Core` as >= 2.3.1

This how ever is wrong. During compiling this raises the error, that the references to the assembly `Dataweb.NShape` are not correct. The compiler error [`BC32207`](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc32207) is raised.

**Comment by kholzinger** [comment]
Thanks for your feedback. 
There is a simple workaround: 
Update to the latest version using the package explorer.

**Comment by mkaring** [comment]
This issue has been resolved a long time ago in version 2.4.1.
